// <auto-generated />
using System;
using FocusMed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusMed.Data.Migrations
{
    [DbContext(typeof(FocusMedDbContext))]
    [Migration("20260828190630_AddPrintAuditEntry")]
    partial class AddPrintAuditEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FocusMed.Data.Entities.AssociationAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalledAeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallingAeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSopClasses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssociationAuditEntries");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DicomImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PngPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DicomImageId");

                    b.ToTable("DicomFrames");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PngPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SopInstanceUid");

                    b.HasIndex("Source");

                    b.ToTable("DicomImages");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrintJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrintJobId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("FilmBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaperSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrintedAt");

                    b.ToTable("PrintAuditEntries");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintImageBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilmBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedImageSopUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmBoxId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("PrintImageBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfCopies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrintPriority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesInstanceUid");

                    b.HasIndex("StudyId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.StorageCommitmentJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallingAet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSopInstanceUids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("StorageCommitmentJobs");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferringPhysicianName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePdfPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.WorklistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedProcedureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledProcedureStepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledProcedureStepStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientName");

                    b.ToTable("WorklistEntries");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomFrame", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.DicomImage", "DicomImage")
                        .WithMany("Frames")
                        .HasForeignKey("DicomImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DicomImage");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Series", "Series")
                        .WithMany("Images")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.PrintJob", "PrintJob")
                        .WithMany("FilmBoxes")
                        .HasForeignKey("PrintJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrintJob");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintImageBox", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.FilmBox", "FilmBox")
                        .WithMany("ImageBoxes")
                        .HasForeignKey("FilmBoxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FilmBox");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintJob", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FocusMed.Data.Entities.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Study", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.Navigation("ImageBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Patient", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintJob", b =>
                {
                    b.Navigation("FilmBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
