// <auto-generated />
using System;
using FocusMed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FocusMed.Data.Migrations
{
    [DbContext(typeof(FocusMedDbContext))]
    [Migration("20260706214141_ConvertStorageCommitmentStatusToEnum")]
    partial class ConvertStorageCommitmentStatusToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FocusMed.Data.Entities.AssociationAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalledAeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallingAeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedSopClasses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AssociationAuditEntries");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DicomImageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PngPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DicomImageId");

                    b.ToTable("DicomFrames");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PngPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("DicomImages");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilmSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrintJobId")
                        .HasColumnType("integer");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrintJobId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("FilmBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintImageBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilmBoxId")
                        .HasColumnType("integer");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ReferencedImageSopUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FilmBoxId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("PrintImageBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfCopies")
                        .HasColumnType("integer");

                    b.Property<string>("PrintPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.StorageCommitmentJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallingAet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedSopInstanceUids")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("StorageCommitmentJobs");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.WorklistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedProcedureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScheduledProcedureStepId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledProcedureStepStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientName");

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("WorklistEntries");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomFrame", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.DicomImage", "DicomImage")
                        .WithMany("Frames")
                        .HasForeignKey("DicomImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DicomImage");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Series", "Series")
                        .WithMany("Images")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.PrintJob", "PrintJob")
                        .WithMany("FilmBoxes")
                        .HasForeignKey("PrintJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintJob");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintImageBox", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.FilmBox", "FilmBox")
                        .WithMany("ImageBoxes")
                        .HasForeignKey("FilmBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmBox");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Study", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.HasOne("FocusMed.Data.Entities.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.DicomImage", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.FilmBox", b =>
                {
                    b.Navigation("ImageBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Patient", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.PrintJob", b =>
                {
                    b.Navigation("FilmBoxes");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Series", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FocusMed.Data.Entities.Study", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
